### ISSUE TITLE
What's the floating % for in the network overview TPS view?

### ISSUE THREAD

**Issue by mvines** [solana-labs/networkexplorer#287]
eg,
![image](https://user-images.githubusercontent.com/1281082/63725482-5c4b1580-c80f-11e9-8513-8b55a6c4c5ed.png)
![image](https://user-images.githubusercontent.com/1281082/63725526-7a187a80-c80f-11e9-95f1-4f7a6e5be56d.png)
![image](https://user-images.githubusercontent.com/1281082/63725515-7258d600-c80f-11e9-8d37-39874fb832f8.png)

Sometimes it shows as negative.  Also what's the difference between "0%" and "0.00%"?

**Comment by sunnygleason** [comment]
As far as I can tell this has been removed? Let us know if it's still there!
