### ISSUE TITLE
Leader pubkey should not be truncated on network overview page

### ISSUE THREAD

**Issue by mvines** [solana-labs/networkexplorer#289]
We can use a smaller font, or rearrange the layout so the full pubkey fits:
![image](https://user-images.githubusercontent.com/1281082/63725637-ccf23200-c80f-11e9-88f4-42af803b75fd.png)

**Comment by sbhargava** [comment]
@mvines I get that, I guess for now, users can click into it and see the full pubkey in the details view. In any case, we can def fix this when design team comes back to us and I can discuss layout changes. Might be good to consolidate some of the little layout tweaks that need to be made so they can redesign/rethink as necessary.

**Comment by manuel-calavera** [comment]
we have tooltip on hover showing full address.

**Comment by CriesofCarrots** [comment]
@manuel-calavera , it looks like the width of the tooltip is bounded by the block itself, which wraps the pubkey and looks weird. Can we keep the pubkey in one line when screen is wide enough to fit it?

![image](https://user-images.githubusercontent.com/3030561/66939211-dd4caf00-efff-11e9-9e77-2e91c4ebaa83.png)
