### ISSUE TITLE
Adjust TdS stage dates

### ISSUE THREAD

**Issue by mvines** [solana-labs/networkexplorer#293]
Time for some better dates:
![image](https://user-images.githubusercontent.com/1281082/63725945-b4364c00-c810-11e9-9649-eeba410d31d8.png)

**Comment by sunnygleason** [comment]
Available at https://edge.explorer.solana.com/tour-de-sol

**Comment by sbhargava** [comment]
Reopening becauseeeeee dates have changed again... I will place in the todo column again. @mvines thoughts on not changing it until the week before the 23rd?

**Comment by mvines** [comment]
Hows about we mark all the three dates as *Coming Soon* to avoid having to continually change them

**Comment by sbhargava** [comment]
@manuel-calavera can we change the parenthesis copy to coming soon until we've nailed the dates in a week or two?
