### ISSUE TITLE
Data-loading animation continues forever on down network

### ISSUE THREAD

**Issue by CriesofCarrots** [solana-labs/networkexplorer#309]
On the Network Overview page, on select of network that isn't up (eg Tour de SOL most days), the loading animation loops forever.
A better UX might be a timeout and message to user about the cause.

**Comment by sbhargava** [comment]
@CriesofCarrots thoughts on...upon timeout, display message 'Data currently unavailable. You can report any issues/give us feedback <here> (github link)'

**Comment by CriesofCarrots** [comment]
That sounds good to me

**Comment by sbhargava** [comment]
@manuel-calavera do you think you could knock this out w/out visuals/mocks? Happy to create a wireframe if you need one.

**Comment by manuel-calavera** [comment]
@sbhargava yes, please, i need design.

**Comment by sbhargava** [comment]
![Screen Shot 2019-09-06 at 2 39 32 PM](https://user-images.githubusercontent.com/1693710/64462130-49a8ca00-d0b4-11e9-8fe2-3feeab541f3c.png)

@manuel-calavera here you go!

**Comment by manuel-calavera** [comment]
@sbhargava what are we doing with central blocks? i mean ranking and active validators table.

**Comment by manuel-calavera** [comment]
@sbhargava  here how it looks like for me per screen

https://www.dropbox.com/s/f2m26ztwwrq3mou/Screenshot%202019-09-09%2014.33.44.png?dl=0

https://www.dropbox.com/s/yl9kag30ldf603v/Screenshot%202019-09-09%2014.34.07.png?dl=0

https://www.dropbox.com/s/l0ligtih021jbj0/Screenshot%202019-09-09%2014.34.23.png?dl=0

do you want to put phrase you provided in every block? it might look not good in terms of ui/ux. please advice.

**Comment by sbhargava** [comment]
Yes, let's put that message only on the box like graphics for now. This is for the use case that no data exists so it's okay if every block/box has it for now. It's helpful if not exactly beautiful. We can revisit after TdS stage 1 w/ design help, but for now, let's add it in. @manuel-calavera
