### ISSUE TITLE
transaction tab(s) data store, API + frontend support

### ISSUE THREAD

**Issue by sunnygleason** [solana-labs/networkexplorer#334]
Problem:

* transactions list & detail pages are not implemented (placeholder pages in webapp)

Solution:

* implement JS code in API and webapp data store to enable features

**Comment by sbhargava** [comment]
@sunnygleason blocked on anything?

**Comment by sunnygleason** [comment]
PR: https://github.com/solana-labs/networkexplorer/pull/405

**Comment by sunnygleason** [comment]
available at http://edge.explorer.solana.com/transactions
