### ISSUE TITLE
Tooltips v1

### ISSUE THREAD

**Issue by sbhargava** [solana-labs/networkexplorer#338]
All these terms have tooltips but on hover, say 'click more to see about undefined' which feels sloppy and when you click on them, they lead to the solana knowledge base book with no reference to the actual term. 
Adding spreadsheet of tooltip copy here: https://docs.google.com/spreadsheets/d/1XKHy6T7EQoBjlkF1kEOUeIPIhJFfXpEnMdhvXZdbqs8/edit#gid=0

Notes:
There is some linking work still yet to do (once the TdS FAQ info is in the knowledge base) but at least everything has a better definition so I'm moving this to the todo column for @manuel-calavera or @sunnygleason to knock out at some point. 

OK I know @manuel-calavera  will be able to make a tooltip link component for this. The
only slightly tricky part I remember is linking to "book" versus "book-edge" depending
on the deployed stage (see the old code below).

https://github.com/solana-labs/blockexplorer/blob/master/src/v2/Bx2HelpLink.jsx

**Comment by sunny** [comment]
Hi @sbhargava! I don't think you meant to mention me, but another `Sunny`. Have a nice day! ☀️
