### ISSUE TITLE
Applications Tab Back End

### ISSUE THREAD

**Issue by sbhargava** [solana-labs/networkexplorer#340]

**Comment by sunnygleason** [comment]
this is similar to blocks & transactions, but not exactly.
there isn't a "list" of applications, so we model it as a "set" of applications active in the past N hours.
PR should follow shortly after the PR #405 is reviewed/approved.

**Comment by sunnygleason** [comment]
merged; should be visible shortly at http://edge.explorer.solana.com/applications
