### ISSUE TITLE
Search for validator only works after stake has warmed up

### ISSUE THREAD

**Issue by CriesofCarrots** [solana-labs/networkexplorer#369]
Search for validator by pubkey or by keybase name returns no result if validator's stake hasn't warmed up yet, even though the validator appears in the validators table and has a details page.

**Comment by sunnygleason** [comment]
I think this is because it's only searching active validators:

https://github.com/solana-labs/networkexplorer/blob/master/src/v2/components/Search/index.jsx#L66

**Comment by manuel-calavera** [comment]
@CriesofCarrots  i hv done as it was simple change on ui level. but as i mentioned in #370 we will move further with api search method.

**Comment by CriesofCarrots** [comment]
I will look for this during the next TdS internal dry run.
