### ISSUE TITLE
Search by keybase name returns results as node pubkeys

### ISSUE THREAD

**Issue by CriesofCarrots** [solana-labs/networkexplorer#370]
It feels weird for search results to not match my input. And also it's hard to pick the right one if names start with the same string!

![image](https://user-images.githubusercontent.com/3030561/64300649-e2b3d580-cf3a-11e9-951d-762a2792f71b.png)

(Nodes above have names: beta-testnet-solana-com-us-west1-b-fullnode2, beta-testnet-solana-com-us-west1-b-fullnode1, beta-testnet-solana-com-bootstrap-leader)

**Comment by manuel-calavera** [comment]
@CriesofCarrots currently we are having simple validators search func in ui code which is not right and has to be reimplemented by using api search method (not implemented by now). so i don't think we need to extend ui code to support all corner cases but rather wait for api layer to be ready to search objects properly.

**Comment by manuel-calavera** [comment]
@CriesofCarrots i still did it because I had nothing to do :)

**Comment by CriesofCarrots** [comment]
Thanks, @manuel-calavera! I think this will be worth it for improved UX for our validators during dryruns and TdS
