### ISSUE TITLE
Add list of inactive validators

### ISSUE THREAD

**Issue by sbhargava** [solana-labs/networkexplorer#399]
Options:

Another table below the active ones or a tab/link near 'active' to toggle back and forth

**Comment by sbhargava** [comment]
https://github.com/solana-labs/networkexplorer/issues/363 @chris-remus

**Comment by sbhargava** [comment]
@chris-remus sadly didn't get time this past week to move this forward, but you had mentioned you had thoughts on layout/design. Would love to hear them before I start wireframing it out.

**Comment by sbhargava** [comment]
![Screen Shot 2019-09-25 at 1 15 45 PM](https://user-images.githubusercontent.com/1693710/65636194-b36f1200-df96-11e9-8e27-24d037df9cf4.png)

@chris-remus thoughts on something like this where you can click and toggle views of active vs inactive validators? Not sure if this a good placement/UI but this approach doesn't mess w/ trying to add another table below.

**Comment by chris-remus** [comment]
Add a tabbed view for "Active" and "Inactive" Validators -

<img width="1678" alt="Screen Shot 2019-10-02 at 1 13 03 PM" src="https://user-images.githubusercontent.com/6430200/66065941-7ff03280-e516-11e9-8051-1573fba4c59a.png">

See the examples here -

<img width="1670" alt="Screen Shot 2019-10-02 at 1 12 32 PM" src="https://user-images.githubusercontent.com/6430200/66065958-8a123100-e516-11e9-94ca-353f375efb57.png">
<img width="1667" alt="Screen Shot 2019-10-02 at 1 12 19 PM" src="https://user-images.githubusercontent.com/6430200/66065959-8a123100-e516-11e9-8c64-c28bc3036d33.png">
