### ISSUE TITLE
Map view of nodes doesn't match number of active validators

### ISSUE THREAD

**Issue by sbhargava** [solana-labs/networkexplorer#434]
<img width="1434" alt="Screen Shot 2019-09-27 at 1 39 26 PM" src="https://user-images.githubusercontent.com/1693710/65800828-64f37c00-e12c-11e9-8035-56efeaa933f8.png">

I only see a dot for one node and on hover, shows one node, but active count is 4?

**Comment by mvines** [comment]
All those 4 nodes are getting placed at the exact same latlong

**Comment by CriesofCarrots** [comment]
Hover over those node points could report how many nodes are there?
