### ISSUE TITLE
What happened to tooltips on the 'See all' validators view?

### ISSUE THREAD

**Issue by sbhargava** [solana-labs/networkexplorer#435]
<img width="1368" alt="Screen Shot 2019-09-27 at 1 42 13 PM" src="https://user-images.githubusercontent.com/1693710/65800945-abe17180-e12c-11e9-8094-ab55bb8690e9.png">

What are these strange numbers and what do they mean????

**Comment by manuel-calavera** [comment]
@sbhargava i did not get what is wrong here. please provide more details (like design reference) and better title :)

**Comment by manuel-calavera** [comment]
@sbhargava i think i got it. you mean that tooltips signs are absent for table columns. there are missing in design as well. i will add them
