### ISSUE TITLE
Copy pubkey icon/link should give some indication it's done something on click

### ISSUE THREAD

**Issue by CriesofCarrots** [solana-labs/networkexplorer#443]

**Comment by sbhargava** [comment]
Should maybe have a hover state and then a tiny banner/flash message that says 'Copied!'. @aaronvaughn to add an example

**Comment by aaronvaughn** [comment]
Example from Google Docs
<img width="556" alt="Screen Shot 2019-09-30 at 2 42 10 PM" src="https://user-images.githubusercontent.com/54717456/65919249-979dae80-e390-11e9-8929-b240af9325b3.png">
