### ISSUE TITLE
Transactions count?

### ISSUE THREAD

**Issue by CriesofCarrots** [solana-labs/networkexplorer#450]
Is this number (far right of screenshot) supposed to be total transaction count?

![image](https://user-images.githubusercontent.com/3030561/65803489-f7e7e280-e13b-11e9-83ef-56143302527c.png)

It seems to go down on refresh sometimes.

**Comment by manuel-calavera** [comment]
@sunnygleason

**Comment by sunnygleason** [comment]
* That data point is actually the number of `browsable` transactions (we have a fixed buffer of them)
* We *do* have the total # of "all time" transactions available as a global statistic
* We are still working out the pagination & refresh display -- we should probably have a quick discussion on how to sort all of this out in an intuitive way for the user

Based on how we want this to be, this specific number isn't a big change to implement. Maybe:

* Go for a quick fix now (replace that # with global transaction count?)
* We file a separate issue for transaction pagination & refresh navigation?

**Comment by CriesofCarrots** [comment]
@sunnygleason Makes sense to handle this issue with pagination/refresh display. I imagine it might need some explanatory words, like "XXXX latest transactions" or "showing XXX recent transactions", or something like that.

Feel free to close this issue if it seems superfluous.

Global transaction count seems a fine quick-fix, but since this page really depends on the pagination/refresh work anyway, I don't feel that change is very high priority.

**Comment by sunnygleason** [comment]
(addressed here via "recent transactions" title text -- can revisit in next round of QA depending on which data point(s) we want to emphasize): https://github.com/solana-labs/networkexplorer/pull/555/files?file-filters%5B%5D=.jsx#diff-3839eedf314a35d50794395979027faaR48)

![image](https://user-images.githubusercontent.com/153621/66960799-4dc4f180-f03b-11e9-8bd8-281bfe62ba68.png)
