### ISSUE TITLE
Keybase avatars disappeared

### ISSUE THREAD

**Issue by CriesofCarrots** [solana-labs/networkexplorer#452]
![image](https://user-images.githubusercontent.com/3030561/65803751-c885a580-e13c-11e9-967f-8692157d1b38.png)

s/b
![image](https://user-images.githubusercontent.com/3030561/65803772-de936600-e13c-11e9-98a1-6a45782e6189.png)

I believe these were displaying during previous dryruns

**Comment by manuel-calavera** [comment]
@sunnygleason could you please check why avatarUrl field in identity object is missing?

**Comment by sunnygleason** [comment]
Looks like the invalid `team/solana` username is blocking the API batch request. Will file a PR to fix...

**Comment by sunnygleason** [comment]
merged - should be visible soon at https://edge.explorer.solana.com/

**Comment by CriesofCarrots** [comment]
I am trying to test this, but keybase.pub is 504 :(
