### ISSUE TITLE
Staked SOL truncated

### ISSUE THREAD

**Issue by CriesofCarrots** [solana-labs/networkexplorer#453]
![image](https://user-images.githubusercontent.com/3030561/65803908-51044600-e13d-11e9-9d6e-8491a6ab14f8.png)

At the least, the whole number should appear on hover. But I would rather that we find some way to handle large numbers in a readable way.
Perhaps we can do a little research into how other sites do this.

**Comment by sbhargava** [comment]
Yeah, let's decrease font size for now. Then rethink layout in a later iteration after mainnet launch.
