### ISSUE TITLE
Website Disclaimer link just goes to solana.com

### ISSUE THREAD

**Issue by CriesofCarrots** [solana-labs/networkexplorer#454]
On solana.com, this link in the footer brings up a popup.
![image](https://user-images.githubusercontent.com/3030561/65804099-f9b2a580-e13d-11e9-986c-b85e27c2e269.png)

But on the networkexplorer, it just goes to solana.com, which is confusing, given the text of the link

**Comment by sbhargava** [comment]
Yep. We should have this pop up:
<img width="1401" alt="Screen Shot 2019-09-30 at 2 50 09 PM" src="https://user-images.githubusercontent.com/1693710/65919592-ac2e7680-e391-11e9-9b7b-c08f4ba46148.png">
