### ISSUE TITLE
Make Discuss on Forums link target="_blank"

### ISSUE THREAD

**Issue by CriesofCarrots** [solana-labs/networkexplorer#455]

**Comment by sbhargava** [comment]
@CriesofCarrots can you elaborate? Link seems to work, do you mean that the arrow design is awful? :-P

**Comment by CriesofCarrots** [comment]
Target is an html attribute that specifies where a link opens. This link opens in the current tab instead of in a new tab, which is what the others do.

(But I'm not crazy about the arrow design either ;) )
