### ISSUE TITLE
TDS Active Validators View: Up Time > 100%

### ISSUE THREAD

**Issue by aaronvaughn** [solana-labs/networkexplorer#456]
![Screen Shot 2019-09-27 at 3 51 10 PM](https://user-images.githubusercontent.com/54717456/65804343-d3d9d080-e13e-11e9-879d-fa39060cbc9e.png)
Up Time stat in Active Validators View in TDS page shows more than 100%.

**Comment by CriesofCarrots** [comment]
@aaronvaughn, @sbhargava  I think this is dependent on https://github.com/solana-labs/networkexplorer/issues/425

Right now, uptime is just calculated as a ratio of number of votes a validator made in an epoch over how many possible blocks there were to vote on. Sometimes votes get held up and processed in the following epoch, which is how the percentage can be greater than 0. I suppose we could default to rounding down to 100% for now, but I don't think it makes sense to spend much time on this until #425 is resolved.

**Comment by aaronvaughn** [comment]
Sounds like a plan @CriesofCarrots

**Comment by sunnygleason** [comment]
@CriesofCarrots @manuel-calavera I'm merging this now, feeling slightly uneasy about it because it masks a calculation/logic bug for a core metric. Will add a fixme there so that we remember to revisit the bandaid code once we have the correct calculation.

**Comment by sunnygleason** [comment]
ok, should be visible at http://edge.explorer.solana.com/
