### ISSUE TITLE
Map is blank

### ISSUE THREAD

**Issue by CriesofCarrots** [solana-labs/networkexplorer#512]
![image](https://user-images.githubusercontent.com/3030561/66325974-6cade000-e8e5-11e9-866d-4cb4e9e457e8.png)

Fyi @manuel-calavera

**Comment by CriesofCarrots** [comment]
Hmm, actually clearing my browser cache seems to have restored it. Is it worth looking into the cause of this?

**Comment by sunnygleason** [comment]
@CriesofCarrots we recently switched from react maps to Google maps, I'm guessing it's stale files locally? Here's the recent change:

https://github.com/solana-labs/networkexplorer/pull/410

**Comment by CriesofCarrots** [comment]
@sunnygleason Yep, I've been seeing the Google maps (last week), but on load today, the map was blank until I cleared my browser cache.

**Comment by manuel-calavera** [comment]
@CriesofCarrots i am not able to repro. can we close it?
