### ISSUE TITLE
Active/Inactive validators font inconsistent with rest of page

### ISSUE THREAD

**Issue by CriesofCarrots** [solana-labs/networkexplorer#561]
On the Figma design, the Active/Inactive Validator tab links are the same size font as the rest of the block headings (Active Validators Map, Circulating SOL, etc). On the live site, the rest of the block headings appear to be 16px height. Drop Active/Inactive Validator tab links from 18px to match.

**Comment by manuel-calavera** [comment]
@CriesofCarrots i am not sure why we want to drop it if figma says 18px. 
![photo_2019-10-17_08-46-09](https://user-images.githubusercontent.com/42587550/67025567-18f87f00-f0bb-11e9-9efd-d2d44a24c7c6.jpg)

**Comment by CriesofCarrots** [comment]
Figma also says 18px for all the other block labels (Active Validators Map, Circulating SOL, etc)
I don't recall when or why we decreased that typeface size, but clearly we did. Please update this to match the rest of the page.
